import { mkdir, writeFile } from 'node:fs/promises';
import { profile, publications, awards, honors } from '../content/profile.mjs';

const root = new URL('../', import.meta.url);
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const accepted = publications.filter(p => ['accepted', 'published'].includes(p.status)).sort((a,b) => b.year - a.year);
for (const paper of accepted) {
  for (const key of ['id','title','authors','venue','year']) if (!paper[key]) throw new Error(`Publication is missing ${key}`);
  if (!Array.isArray(paper.authors) || !paper.authors.length) throw new Error('Publication authors must be a nonempty array');
  if (paper.equalContribution && (!Array.isArray(paper.equalContribution) || paper.equalContribution.some(name => !paper.authors.includes(name)))) throw new Error('Equal-contribution names must appear in the author list');
  if (paper.overview && (!paper.overview.thumbnail?.startsWith('assets/publications/') || !paper.overview.full?.startsWith('assets/publications/') || !paper.overview.alt?.zh || !paper.overview.alt?.en || !(paper.overview.width > 0 && paper.overview.height > 0))) throw new Error('Publication overview requires local assets, dimensions, and bilingual alternative text');
  for (const key of ['paper','code','doi']) if (paper[key] && !/^https:\/\//.test(paper[key])) throw new Error(`${key} must be an HTTPS URL`);
}
const icons = {
  arrow: '<path d="M7 17 17 7M7 7h10v10"/>',
  right: '<path d="M4 12h16m-6-6 6 6-6 6"/>',
  mail: '<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 6 9 7 9-7"/>',
  github: '<path d="M9 19c-4.3 1.3-4.3-2.2-6-2.7M15 22v-3.9c.1-1-.3-1.8-.8-2.3 2.8-.3 5.8-1.4 5.8-6.3A4.9 4.9 0 0 0 18.7 6 4.5 4.5 0 0 0 18.6 2s-1.1-.3-3.6 1.4a12.1 12.1 0 0 0-6 0C6.5 1.7 5.4 2 5.4 2A4.5 4.5 0 0 0 5.3 6 4.9 4.9 0 0 0 4 9.5c0 4.9 3 6 5.8 6.3-.5.5-.9 1.3-.8 2.3V22"/>',
  network: '<circle cx="12" cy="5" r="2"/><circle cx="5" cy="17" r="2"/><circle cx="19" cy="17" r="2"/><path d="m11 7-5 8m7-8 5 8M7 17h10"/>',
  shield: '<path d="m12 3 8 3v6c0 4-4 7-8 9-4-2-8-5-8-9V6l8-3Z"/><path d="m8 12 3 3 5-6"/>',
  layers: '<path d="m12 3 10 6-10 6L2 9l10-6Zm-10 12 10 6 10-6M2 12l10 6 10-6"/>',
  award: '<circle cx="12" cy="8" r="5"/><path d="m8 12-2 9 6-3 6 3-2-9"/>',
  book: '<path d="M12 5v16M3 3c4-1 6 0 9 2 3-2 5-3 9-2v16c-4-1-6 0-9 2-3-2-5-3-9-2V3Z"/>',
  close: '<path d="m6 6 12 12M6 18 18 6"/>',
  copy: '<rect x="8" y="8" width="12" height="13" rx="2"/><path d="M16 8V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h3"/>',
  menu: '<path d="M4 7h16M4 12h16M4 17h16"/>'
};
const icon = (name, cls='') => `<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]}</svg>`;

for (const lang of ['zh', 'en']) {
 const en = lang === 'en';
 const t = value => typeof value === 'object' ? value[lang] : value;
 const tr = (zh,eng) => en ? eng : zh;
 const base = en ? '../' : './';
 const title = tr('王亿宽 | 武汉大学 · 学术主页','Yikuan Wang | Wuhan University');
 const description = tr('王亿宽，武汉大学国家网络安全学院硕士研究生。研究方向包括大语言模型安全、多智能体系统与多模态感知。','Yikuan Wang, a master’s student at Wuhan University researching LLM security, multi-agent systems, and multimodal perception.');
 const certificate = (file, label, name) => `<a class="certificate-link" href="${base}assets/certificates/${esc(file)}" data-certificate data-title="${esc(name)}" aria-label="${esc(name + ' · ' + label)}">${esc(label)}${icon('arrow')}</a>`;
 const head = (id, number, english, name, sub='') => `<div class="section-heading"><div><p class="eyebrow"><span>${number}</span>${english}</p><h2 id="${id}-title">${name}</h2></div>${sub ? `<p class="section-description">${sub}</p>` : ''}</div>`;
 const nav = [['research',tr('研究方向','Research')],['publications',tr('学术成果','Publications')],['awards',tr('奖项与荣誉','Recognition')],['experience',tr('教育与经历','Experience')]];
 const prize = n => en ? ({1:'First Prize',2:'Second Prize',3:'Third Prize'})[n] : ({1:'一等奖',2:'二等奖',3:'三等奖'})[n];
 const level = value => value === 'national' ? tr('国家级','National') : tr('省部级','Regional');
 const renderPublication = p => {
  const venue = `<div class="publication-venue"><strong>${esc(p.venue)}</strong><span>${esc(p.year)}</span></div>`;
  const authors = p.authors.map(name => {
   const label = /^(Yikuan Wang|王亿宽)$/.test(name) ? `<strong>${esc(name)}</strong>` : esc(name);
   return label + (p.equalContribution?.includes(name) ? '<sup class="author-marker">*</sup>' : '');
  }).join(', ');
  const overview = p.overview ? `<figure class="publication-overview">${venue}<a href="${base}${esc(p.overview.full)}" target="_blank" rel="noopener noreferrer" aria-label="${esc(tr('查看 RIGOR 完整框架图（新窗口）','View the full RIGOR overview (new tab)').replace('RIGOR',p.id.toUpperCase()))}"><img src="${base}${esc(p.overview.thumbnail)}" width="${p.overview.width}" height="${p.overview.height}" alt="${esc(t(p.overview.alt))}" loading="lazy" decoding="async"></a><figcaption>${esc(p.id.toUpperCase())} · ${tr('方法概览','Framework overview')}</figcaption></figure>` : venue;
  return `<article class="publication" id="paper-${esc(p.id)}"${p.overview ? ' data-with-overview' : ''}>
${overview}<div class="publication-content"><p class="paper-status">${p.status === 'accepted' ? tr('已录用','Accepted') : tr('已发表','Published')}${p.presentation ? ` <span aria-hidden="true">·</span> ${esc(p.presentation)}` : ''}</p>
<h3>${p.paper ? `<a href="${esc(p.paper)}" target="_blank" rel="noopener noreferrer">${esc(p.title)}</a>` : esc(p.title)}</h3><p class="authors">${authors}</p>
${p.equalContribution?.length ? `<p class="contribution-note">* ${tr('共同第一作者','Co-first author')}</p>` : ''}
${p.summary ? `<p class="paper-summary">${esc(t(p.summary))}</p>` : ''}
<div class="paper-links">${[['paper',tr('论文 PDF','Paper PDF')],['doi','DOI'],['code',tr('代码','Code')]].filter(([key])=>p[key]).map(([key,label])=>`<a href="${esc(p[key])}" target="_blank" rel="noopener noreferrer">${label}${icon('arrow')}</a>`).join('')}${p.bibtex ? `<details><summary>BibTeX</summary><pre>${esc(p.bibtex)}</pre><button type="button" class="copy-bibtex">${tr('复制引用','Copy citation')}</button></details>` : ''}</div></div></article>`;
 };
 const paperHTML = accepted.length ? `<div class="publication-list">${accepted.map(renderPublication).join('')}</div>` : `<div class="publication-empty">${icon('book')}<div><h3>${tr('学术成果', 'Publications')}</h3><p>${tr('论文信息将在确认后更新。', 'Publication details will be added once confirmed.')}</p></div><span class="quiet-label">${tr('持续更新', 'Updates to follow')}</span></div>`;
 const html = `<!doctype html>
<html lang="${en ? 'en' : 'zh-CN'}">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light">
<title>${title}</title><meta name="description" content="${description}"><meta name="theme-color" content="#172e46">
<link rel="canonical" href="https://onewide.github.io/${en ? 'en/' : ''}"><link rel="alternate" hreflang="zh-CN" href="https://onewide.github.io/"><link rel="alternate" hreflang="en" href="https://onewide.github.io/en/"><link rel="alternate" hreflang="x-default" href="https://onewide.github.io/">
<meta property="og:type" content="profile"><meta property="og:title" content="${title}"><meta property="og:description" content="${description}"><meta property="og:url" content="https://onewide.github.io/${en ? 'en/' : ''}"><meta property="og:image" content="https://onewide.github.io/assets/social-card.png"><meta property="og:locale" content="${en ? 'en_US' : 'zh_CN'}"><meta name="twitter:card" content="summary_large_image">
<link rel="icon" type="image/svg+xml" href="${base}assets/favicon.svg"><link rel="stylesheet" href="${base}assets/site.css"><link rel="stylesheet" href="${base}assets/publications.css"><script src="${base}assets/site.js" defer></script>
<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'Person',name:'Yikuan Wang',alternateName:'王亿宽',url:'https://onewide.github.io/',image:'https://onewide.github.io/assets/portrait.webp',email:profile.email,affiliation:{'@type':'CollegeOrUniversity',name:'Wuhan University'},sameAs:[profile.github],knowsAbout:['Large Language Model Security','Multi-Agent Systems','Multimodal Perception']})}</script>
</head>
<body>
<a class="skip-link" href="#main">${tr('跳转至主要内容','Skip to content')}</a>
<header class="site-header"><div class="container header-inner"><a class="wordmark" href="${base}" aria-label="${tr('王亿宽，主页','Yikuan Wang, home')}"><span class="monogram">YW<span>.</span></span><span class="wordmark-name">YIKUAN WANG</span></a><button class="menu-toggle" type="button" aria-label="${tr('展开导航','Toggle navigation')}" aria-expanded="false" aria-controls="navigation">${icon('menu')}</button><nav id="navigation" aria-label="${tr('主要导航','Main navigation')}">${nav.map(([id,label])=>`<a href="#${id}">${label}</a>`).join('')}</nav><a class="language-link" href="${en ? '../' : './en/'}" lang="${en ? 'zh-CN' : 'en'}" hreflang="${en ? 'zh-CN' : 'en'}">${en ? '中文' : 'EN'}${icon('arrow')}</a></div></header>
<main id="main">
<section class="hero container" aria-labelledby="hero-title"><div class="hero-copy"><p class="eyebrow hero-eyebrow"><span class="small-rule"></span>WUHAN UNIVERSITY</p><h1 id="hero-title">${en ? 'Yikuan <em>Wang.</em>' : '王亿宽<span class="name-dot">.</span>'}</h1><p class="hero-romanization">${en ? '王亿宽' : 'Yikuan Wang'}</p><p class="hero-role">${esc(t(profile.role))}</p><p class="hero-school">${esc(t(profile.school))} <span>/</span> ${esc(t(profile.university))}</p><p class="hero-intro">${esc(t(profile.intro))}</p><div class="hero-actions"><a class="button button-primary" href="mailto:${profile.email}">${icon('mail')}${tr('邮件联系','Get in touch')}${icon('arrow')}</a><a class="button button-text" href="${profile.github}" target="_blank" rel="noopener noreferrer">${icon('github')}GitHub${icon('arrow')}</a></div><div class="hero-topics"><span>LLM Security</span><span>Multi-Agent Systems</span><span>Multimodal AI</span></div></div><figure class="portrait-composition"><div class="portrait-corner" aria-hidden="true"></div><div class="portrait-frame"><img src="${base}assets/portrait.webp" alt="${tr('王亿宽的个人照片','Portrait of Yikuan Wang')}" width="800" height="1120" fetchpriority="high"><div class="portrait-caption"><span>${tr('武汉，中国','Wuhan, China')}</span><span>30.54° N / 114.36° E</span></div></div><figcaption><span class="status-dot"></span>${tr('探索可信赖的智能系统','Exploring trustworthy intelligent systems')}</figcaption><span class="portrait-index" aria-hidden="true">RESEARCH · CURIOSITY · IMPACT</span></figure></section>
<div class="hero-foot container"><span>AI SECURITY & INTELLIGENT SYSTEMS</span><a href="#research">${tr('向下探索','Explore below')}<span aria-hidden="true">↓</span></a></div>
<section id="research" class="section container" aria-labelledby="research-title">${head('research','01','RESEARCH INTERESTS',tr('研究方向','Research interests'),tr('理解智能系统的边界，探索更安全、可靠的人工智能。','Understanding the boundaries of intelligent systems to build safer, more reliable AI.'))}<div class="research-grid">${profile.interests.map(r=>`<article class="research-card"><div class="research-top">${icon(r.icon)}<span>${r.id}</span></div><h3>${esc(t(r.name))}</h3>${!en ? `<p class="research-english">${r.english}</p>` : ''}<p class="research-description">${esc(t(r.description))}</p><div class="topic-tags">${r.tags.map(tag=>`<span>${esc(tag)}</span>`).join('')}</div></article>`).join('')}</div></section>
<section id="publications" class="section publications-section" aria-labelledby="publications-title"><div class="container">${head('publications','02','PUBLICATIONS',tr('学术成果','Publications'),tr('围绕大模型安全与智能体系统的研究。','Research on the security of large language models and agent systems.'))}${paperHTML}</div></section>
<section id="awards" class="section container" aria-labelledby="awards-title">${head('awards','03','AWARDS & HONORS',tr('竞赛奖项与荣誉','Awards & honors'),tr('从理论探索到工程实践。','From theoretical exploration to engineering practice.'))}<div class="recognition-highlights"><div class="highlight-label">${icon('award')}<span>${tr('精选竞赛奖项','Selected distinctions')}</span></div><div><strong>${tr('全国一等奖','National First Prize')}</strong><span>${tr('中国机器人及人工智能大赛 · 2025','China Robot and AI Competition · 2025')}</span></div><div><strong>${tr('全国一等奖','National First Prize')}</strong><span>${tr('全国大学生数学竞赛 · 2024','Chinese Mathematics Competitions · 2024')}</span></div></div><div class="awards-toolbar"><h3>${tr('竞赛获奖','Competition awards')}</h3><div class="award-filters" role="group" aria-label="${tr('按奖项级别筛选','Filter awards by level')}"><button type="button" data-filter="all" aria-pressed="true">${tr('全部','All')}<span>${awards.length}</span></button><button type="button" data-filter="national" aria-pressed="false">${tr('国家级','National')}<span>${awards.filter(a=>a.level==='national').length}</span></button><button type="button" data-filter="regional" aria-pressed="false">${tr('省部级','Regional')}<span>${awards.filter(a=>a.level==='regional').length}</span></button></div></div><p class="sr-only" id="filter-status" role="status" aria-live="polite"></p><div class="awards-list">${awards.map(a=>`<article class="award-row" data-level="${a.level}"><span class="award-year">${a.year}</span><div class="award-name"><h4>${esc(t(a.name))}</h4><p>${esc(t(a.track))}</p></div><span class="prize-badge ${a.level==='national' ? 'national' : ''}"><span>${level(a.level)}</span>${prize(a.prize)}</span>${certificate(a.certificate,tr('证书','Certificate'),`${t(a.name)} · ${a.year} · ${level(a.level)}${prize(a.prize)}`)}</article>`).join('')}</div><div class="honors-heading"><h3>${tr('奖学金与个人荣誉','Scholarships & distinctions')}</h3><span>HONORS & SCHOLARSHIPS</span></div><div class="honors-grid">${honors.map(h=>`<article class="honor-card"><span class="honor-year">${h.year}</span><h4>${esc(t(h.title))}</h4><p>${esc(t(h.description))}</p>${h.certificates ? `<div class="honor-links">${h.certificates.map(c=>certificate(c.file,c.label || tr('证书','Certificate'),t(h.title))).join('')}</div>` : ''}</article>`).join('')}</div></section>
<section id="experience" class="section experience-section" aria-labelledby="experience-title"><div class="container">${head('experience','04','EDUCATION & SERVICE',tr('教育与服务经历','Education & service'))}<div class="experience-grid"><div class="education"><h3 class="subsection-title">${tr('教育背景','Education')}</h3><div class="timeline">${profile.education.map(e=>`<article class="education-item"><span class="timeline-dot ${e.current ? 'current' : ''}" aria-hidden="true"></span><p class="education-period">${esc(t(e.period))}${e.current ? `<span class="current-label">${tr('在读','Current')}</span>` : ''}</p><h4>${esc(t(profile.university))}</h4><p class="education-degree">${esc(t(e.degree))}</p><p class="education-school">${esc(t(profile.school))}</p><p class="education-detail">${esc(t(e.detail))}</p></article>`).join('')}</div></div><div class="service"><h3 class="subsection-title">${tr('学生工作','Service & leadership')}</h3><article class="service-card"><div class="service-header"><span class="service-mark" aria-hidden="true">W.</span><span>${profile.service.period}</span></div><h4>${esc(t(profile.service.title))}</h4><p class="service-organization">${esc(t(profile.service.organization))}</p><p class="service-description">${esc(t(profile.service.description))}</p>${certificate(profile.service.certificate,tr('任职证明','Appointment certificate'),t(profile.service.title))}</article></div></div></div></section>
<section id="contact" class="contact-section container" aria-labelledby="contact-title"><div><p class="eyebrow">LET’S CONNECT</p><h2 id="contact-title">${tr('交流，让想法生长。','Good ideas start with a conversation.')}</h2><p>${tr('欢迎就大模型安全、多智能体系统及相关研究与我交流。','I welcome conversations about LLM security, multi-agent systems, and related research.')}</p></div><div class="contact-actions"><a class="email-link" href="mailto:${profile.email}">${profile.email}${icon('arrow')}</a><button class="copy-email" type="button" data-email="${profile.email}" aria-label="${tr('复制邮箱地址','Copy email address')}">${icon('copy')}<span>${tr('复制邮箱','Copy email')}</span></button><span id="copy-status" class="copy-status" role="status" aria-live="polite"></span></div></section>
</main>
<footer class="site-footer"><div class="container footer-inner"><p>© 2026 ${tr('王亿宽','Yikuan Wang')}<span>Wuhan University</span></p><a href="#main">${tr('返回顶部','Back to top')} ↑</a></div></footer>
<dialog id="certificate-dialog" aria-labelledby="certificate-title"><div class="dialog-header"><h2 id="certificate-title"></h2><button type="button" class="dialog-close" aria-label="${tr('关闭证书','Close certificate')}">${icon('close')}</button></div><div class="certificate-image-wrap"><img id="certificate-image" alt=""></div><div class="dialog-footer"><a id="certificate-original" target="_blank" rel="noopener noreferrer">${tr('在新窗口查看','Open in new tab')}${icon('arrow')}</a><span>Esc ${tr('关闭','to close')}</span></div></dialog>
</body></html>`;
 const destination = new URL(en ? 'en/' : './', root);
 await mkdir(destination, {recursive:true});
 await writeFile(new URL('index.html', destination), html);
}
await writeFile(new URL('robots.txt', root),'User-agent: *\nAllow: /\nSitemap: https://onewide.github.io/sitemap.xml\n');
await writeFile(new URL('sitemap.xml', root),'<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>https://onewide.github.io/</loc></url><url><loc>https://onewide.github.io/en/</loc></url></urlset>\n');
console.log(`Built Chinese and English pages. ${accepted.length} confirmed publications, ${awards.length} competition awards.`);
